// Catalog data only. Site-level settings live in site-config.js.

(function (window) {
  "use strict";

  function imageSet(productId, count) {
    return Array.from({ length: count }, (_, index) => {
      const imageNumber = String(index + 1).padStart(2, "0");
      return `images/${productId}-${imageNumber}.webp`;
    });
  }

  function createProduct(product) {
    const galleryImages = product.galleryImages || imageSet(product.id, product.imageCount || 1);

    return {
      id: product.id,
      name: product.name,
      image: product.image || galleryImages[0],
      description: product.description,
      features: product.features || [],
      specifications: product.specifications || {},
      price: product.price,
      distributorContact: product.distributorContact || null,
      category: product.category,
      featured: Boolean(product.featured),
      galleryImages,
      tags: product.tags || [],
      accentColor: product.accentColor || "#2f6f73",
      videoUrl: product.videoUrl || "",
    };
  }

  const productList = [
    createProduct({
      id: "product-001",
      name: "Blush Celebration Box",
      description: "A bright, gift-ready item with a cheerful finish and a polished presentation.",
      features: ["Gift-ready presentation", "Bright color detail", "Works well for small celebrations"],
      specifications: { availability: "Available weekly", format: "Single featured item", leadTime: "2 days" },
      price: 24,
      category: "featured",
      featured: true,
      imageCount: 5,
      tags: ["celebration", "gift", "bright"],
      accentColor: "#b83584",
    }),
    createProduct({
      id: "product-002",
      name: "Amber Reserve Set",
      description: "A warm-toned showcase item with layered details and a refined finish.",
      features: ["Layered visual detail", "Premium presentation", "Popular as a gift"],
      specifications: { availability: "Limited run", format: "Small set", leadTime: "3 days" },
      price: 32,
      category: "limited-run",
      imageCount: 5,
      tags: ["amber", "premium", "limited"],
      accentColor: "#8a5a24",
    }),
    createProduct({
      id: "product-003",
      name: "Midnight Studio Piece",
      description: "A high-contrast item designed for clean photography and simple display.",
      features: ["Bold contrast", "Display-friendly shape", "Compact footprint"],
      specifications: { availability: "Made to order", format: "Single item", leadTime: "2 days" },
      price: 18,
      category: "everyday",
      imageCount: 5,
      tags: ["contrast", "studio", "display"],
      accentColor: "#2f3136",
    }),
    createProduct({
      id: "product-004",
      name: "Everyday Mix Pack",
      description: "A flexible assortment for repeat ordering, sampling, or casual gifting.",
      features: ["Assorted details", "Easy to reorder", "Balanced visual variety"],
      specifications: { availability: "Regular stock", format: "Assortment", leadTime: "1 day" },
      price: 28,
      category: "everyday",
      imageCount: 4,
      tags: ["assortment", "popular", "repeat"],
      accentColor: "#8c7224",
    }),
    createProduct({
      id: "product-005",
      name: "Heritage Gift Bar",
      description: "A compact product with a rich finish and a classic gift-shop feel.",
      features: ["Compact package", "Rich finish", "Good for add-on sales"],
      specifications: { availability: "Regular stock", format: "Packaged item", leadTime: "1 day" },
      price: 14,
      category: "gift-ready",
      imageCount: 4,
      tags: ["heritage", "compact", "gift"],
      accentColor: "#7b4a24",
    }),
    createProduct({
      id: "product-006",
      name: "Ruby Accent Piece",
      description: "A vivid product with a deep color accent and a neat finished look.",
      features: ["Color-forward design", "Clean edge detail", "Strong shelf presence"],
      specifications: { availability: "Seasonal stock", format: "Single item", leadTime: "2 days" },
      price: 20,
      category: "seasonal",
      imageCount: 4,
      tags: ["ruby", "seasonal", "color"],
      accentColor: "#9f1d2f",
    }),
    createProduct({
      id: "product-007",
      name: "Classic Trio Pack",
      description: "A familiar, approachable item that fits broad storefront categories.",
      features: ["Recognizable style", "Family-friendly size", "Works in bundles"],
      specifications: { availability: "Regular stock", format: "Three-piece set", leadTime: "1 day" },
      price: 26,
      category: "collections",
      imageCount: 5,
      tags: ["classic", "bundle", "approachable"],
      accentColor: "#94613a",
    }),
    createProduct({
      id: "product-008",
      name: "Golden Sandwich Set",
      description: "A soft-toned product with a layered profile and a premium display feel.",
      features: ["Layered presentation", "Warm color palette", "Photographs clearly"],
      specifications: { availability: "Limited run", format: "Paired item", leadTime: "3 days" },
      price: 30,
      category: "limited-run",
      imageCount: 4,
      tags: ["gold", "paired", "limited"],
      accentColor: "#aa7b3e",
    }),
    createProduct({
      id: "product-009",
      name: "British Market Box",
      description: "A collectible-style item with a sturdy visual presence and premium finish.",
      features: ["Market-ready look", "Dense visual detail", "Good for showcase pages"],
      specifications: { availability: "Limited run", format: "Boxed item", leadTime: "3 days" },
      price: 34,
      category: "collections",
      imageCount: 4,
      tags: ["market", "boxed", "collectible"],
      accentColor: "#5c3725",
    }),
    createProduct({
      id: "product-010",
      name: "Black and White Bundle",
      description: "A simple bundle built around strong contrast and clean presentation.",
      features: ["Clear contrast", "Bundle-friendly", "Easy catalog photography"],
      specifications: { availability: "Regular stock", format: "Bundle", leadTime: "1 day" },
      price: 22,
      category: "everyday",
      imageCount: 4,
      tags: ["bundle", "contrast", "simple"],
      accentColor: "#333333",
    }),
    createProduct({
      id: "product-011",
      name: "Heathridge Fudge Piece",
      description: "A rich, compact item for storefronts that need a premium individual product.",
      features: ["Premium finish", "Compact display size", "Strong close-up detail"],
      specifications: { availability: "Made to order", format: "Single item", leadTime: "2 days" },
      price: 19,
      category: "gift-ready",
      imageCount: 4,
      tags: ["premium", "compact", "rich"],
      accentColor: "#6a321f",
    }),
    createProduct({
      id: "product-012",
      name: "Crisp Square Pack",
      description: "A light, stackable product suited to quick browsing and simple ordering.",
      features: ["Stackable format", "Clear package silhouette", "Easy add-on item"],
      specifications: { availability: "Regular stock", format: "Square pack", leadTime: "1 day" },
      price: 16,
      category: "everyday",
      imageCount: 4,
      tags: ["square", "stackable", "quick"],
      accentColor: "#2f6f73",
    }),
    createProduct({
      id: "product-013",
      name: "Velvet Reserve Item",
      description: "A refined product with a dark finish and optional media support.",
      features: ["Deep color finish", "Premium positioning", "Video-ready product record"],
      specifications: { availability: "Limited run", format: "Single item", leadTime: "3 days" },
      price: 29,
      category: "limited-run",
      imageCount: 4,
      tags: ["velvet", "premium", "media"],
      accentColor: "#573024",
      videoUrl: "https://www.youtube.com/shorts/h2pDgsDiEv8",
    }),
    createProduct({
      id: "product-014",
      name: "High Street Collection",
      description: "A small collection item with a warm finish and optional product video.",
      features: ["Collection-friendly", "Warm visual tone", "Optional video support"],
      specifications: { availability: "Made to order", format: "Small collection", leadTime: "2 days" },
      price: 31,
      category: "collections",
      imageCount: 4,
      tags: ["collection", "warm", "video"],
      accentColor: "#7c4e2a",
      videoUrl: "https://www.youtube.com/shorts/wIAtMzUSFHI",
    }),
    createProduct({
      id: "product-015",
      name: "Holiday Accent Pack",
      description: "A seasonal pack with bright accents for limited-time merchandising.",
      features: ["Seasonal color", "Giftable format", "Limited calendar use"],
      specifications: { availability: "Seasonal stock", format: "Accent pack", leadTime: "3 days" },
      price: 27,
      category: "seasonal",
      imageCount: 4,
      tags: ["holiday", "seasonal", "gift"],
      accentColor: "#a83a2f",
      videoUrl: "https://www.youtube.com/shorts/V8w1FR6SCSM",
    }),
    createProduct({
      id: "product-016",
      name: "Caramel Display Piece",
      description: "A rounded showcase item suited to product pages with larger image galleries.",
      features: ["Large hero image support", "Display-ready shape", "Elegant finish"],
      specifications: { availability: "Made to order", format: "Display item", leadTime: "4 days" },
      price: 36,
      category: "gift-ready",
      imageCount: 4,
      tags: ["display", "elegant", "gift"],
      accentColor: "#6f5948",
      videoUrl: "https://www.youtube.com/shorts/g6cSvJr3fzw",
    }),
    createProduct({
      id: "product-017",
      name: "Signature Chip Pack",
      description: "A familiar format with simple specs for everyday product catalogs.",
      features: ["Familiar profile", "Simple ordering", "Works in multipacks"],
      specifications: { availability: "Regular stock", format: "Pack", leadTime: "1 day" },
      price: 21,
      category: "everyday",
      imageCount: 4,
      tags: ["signature", "pack", "everyday"],
      accentColor: "#8a6445",
      videoUrl: "https://www.youtube.com/shorts/SEFPr8NGXiY",
    }),
    createProduct({
      id: "product-018",
      name: "Soft Gold Pair",
      description: "A soft-toned paired product with a simple, approachable presentation.",
      features: ["Paired format", "Soft visual tone", "Friendly everyday option"],
      specifications: { availability: "Regular stock", format: "Pair", leadTime: "1 day" },
      price: 18,
      category: "everyday",
      imageCount: 4,
      tags: ["pair", "soft", "gold"],
      accentColor: "#a68a28",
      videoUrl: "https://www.youtube.com/shorts/Q-Cp2_iJrfc",
    }),
    createProduct({
      id: "product-019",
      name: "Harvest Cup Set",
      description: "A seasonal item with warm tones and straightforward product details.",
      features: ["Seasonal styling", "Compact set", "Easy to browse on mobile"],
      specifications: { availability: "Seasonal stock", format: "Cup set", leadTime: "2 days" },
      price: 24,
      category: "seasonal",
      imageCount: 4,
      tags: ["harvest", "seasonal", "compact"],
      accentColor: "#8d552f",
    }),
    createProduct({
      id: "product-020",
      name: "Golden Accent Item",
      description: "A bright product with a golden finish and simple storefront positioning.",
      features: ["Bright accent", "Gift-friendly", "Clear gallery images"],
      specifications: { availability: "Limited run", format: "Single item", leadTime: "2 days" },
      price: 25,
      category: "limited-run",
      imageCount: 4,
      tags: ["golden", "accent", "gift"],
      accentColor: "#9d6b27",
    }),
    createProduct({
      id: "product-021",
      name: "October Showcase Bar",
      description: "A seasonal showcase product with high-contrast details and strong photography.",
      features: ["Seasonal theme", "High-contrast look", "Strong close-up images"],
      specifications: { availability: "Seasonal stock", format: "Showcase bar", leadTime: "3 days" },
      price: 23,
      category: "seasonal",
      imageCount: 4,
      tags: ["seasonal", "showcase", "contrast"],
      accentColor: "#b8532d",
    }),
    createProduct({
      id: "product-022",
      name: "Pretzel Caramel Pack",
      description: "A textured product pack for galleries that need clear feature lists.",
      features: ["Textured finish", "Giftable pack", "Strong detail photos"],
      specifications: { availability: "Made to order", format: "Pack", leadTime: "2 days" },
      price: 28,
      category: "gift-ready",
      imageCount: 4,
      tags: ["textured", "caramel", "gift"],
      accentColor: "#6f5130",
    }),
    createProduct({
      id: "product-023",
      name: "Mountain Assortment",
      description: "A varied collection item for product lists that support broad tagging.",
      features: ["Assorted details", "Collection format", "Good for discovery browsing"],
      specifications: { availability: "Limited run", format: "Assortment", leadTime: "3 days" },
      price: 33,
      category: "collections",
      imageCount: 5,
      tags: ["assortment", "collection", "discovery"],
      accentColor: "#3d3d3d",
    }),
    createProduct({
      id: "product-024",
      name: "Green Studio Item",
      description: "A calm, color-forward item with a concise product record.",
      features: ["Distinct color", "Compact gallery", "Easy feature scanning"],
      specifications: { availability: "Made to order", format: "Single item", leadTime: "2 days" },
      price: 20,
      category: "featured",
      imageCount: 3,
      tags: ["green", "studio", "compact"],
      accentColor: "#527f3d",
    }),
    createProduct({
      id: "product-025",
      name: "Emerald Market Piece",
      description: "A limited item with a rich color story and clear gallery support.",
      features: ["Rich color story", "Limited positioning", "Detailed image set"],
      specifications: { availability: "Limited run", format: "Single item", leadTime: "4 days" },
      price: 35,
      category: "limited-run",
      imageCount: 4,
      tags: ["emerald", "market", "limited"],
      accentColor: "#275d38",
    }),
    createProduct({
      id: "product-026",
      name: "Orchard Cup Set",
      description: "A seasonal cup-style item with tidy specifications and gallery images.",
      features: ["Seasonal color", "Cup-style format", "Good small-batch item"],
      specifications: { availability: "Seasonal stock", format: "Cup set", leadTime: "2 days" },
      price: 24,
      category: "seasonal",
      imageCount: 4,
      tags: ["orchard", "cup", "seasonal"],
      accentColor: "#a34f36",
    }),
    createProduct({
      id: "product-027",
      name: "Peach Studio Piece",
      description: "A soft, bright product for storefronts that need approachable featured items.",
      features: ["Soft color finish", "Approachable display", "Flexible category use"],
      specifications: { availability: "Seasonal stock", format: "Single item", leadTime: "2 days" },
      price: 22,
      category: "featured",
      imageCount: 4,
      tags: ["soft", "bright", "featured"],
      accentColor: "#bf7a52",
    }),
    createProduct({
      id: "product-028",
      name: "Mini Variety Cups",
      description: "A playful small-format collection for family-friendly storefront browsing.",
      features: ["Small-format set", "Variety presentation", "Easy mobile scanning"],
      specifications: { availability: "Regular stock", format: "Mini set", leadTime: "1 day" },
      price: 19,
      category: "collections",
      imageCount: 4,
      tags: ["mini", "variety", "family"],
      accentColor: "#9c7b22",
    }),
    createProduct({
      id: "product-029",
      name: "Archive Collection",
      description: "A flexible archive record for older products, retired items, or portfolio work.",
      features: ["Large gallery support", "Archive-friendly", "Useful for retired items"],
      specifications: { availability: "Archive only", format: "Collection", leadTime: "Contact for details" },
      price: null,
      category: "collections",
      imageCount: 8,
      tags: ["archive", "collection", "portfolio"],
      accentColor: "#5f6f7a",
    }),
  ];

  const productData = Object.fromEntries(productList.map((product) => [product.id, product]));

  window.StorefrontProducts = productData;
})(window);
