// Catalog data only. Site-level settings live in site-config.js.
// See docs/MAINTENANCE.md for the complete product schema and add-product steps.

(function (window) {
  "use strict";

  // Builds convention-based paths such as images/product-001-01.webp.
  function imageSet(productId, count) {
    return Array.from({ length: count }, (_, index) => {
      const imageNumber = String(index + 1).padStart(2, "0");
      return `images/${productId}-${imageNumber}.webp`;
    });
  }

  // Normalizes optional fields so every renderer receives a stable record shape.
  function createProduct(product) {
    const galleryImages = product.galleryImages || imageSet(product.id, product.imageCount || 1);

    return {
      id: product.id,
      name: product.name,
      image: product.image || galleryImages[0],
      description: product.description,
      features: product.features || [],
      specifications: product.specifications || {},
      price: product.price,
      distributorContact: product.distributorContact || null,
      category: product.category,
      featured: product.featured === true,
      galleryImages,
      tags: product.tags || [],
      accentColor: product.accentColor || "#2f6f73",
      videoUrl: product.videoUrl || "",
    };
  }

  /*
   * Product IDs and image counts stay aligned with the existing image library.
   * Use featured: true for carousel inclusion. Do not use a featured category
   * or tag because filtering also relies on the boolean.
   */
  const productList = [
    createProduct({
      id: "product-001",
      name: "Morning Pearl Pendant",
      description: "A softly luminous pendant with an easy, graceful shape for everyday wear.",
      features: ["Lightweight feel", "Classic pearl-inspired detail", "Easy to layer or wear alone"],
      specifications: { availability: "In stock", material: "Gold tone and pearl detail", size: "18-inch chain" },
      price: 68,
      category: "necklaces",
      featured: true,
      imageCount: 5,
      tags: ["pearl", "gold", "classic", "gift"],
      accentColor: "#9a7a45",
    }),
    createProduct({
      id: "product-002",
      name: "Amber Light Earrings",
      description: "Warm amber tones give this polished pair a gentle glow and timeless character.",
      features: ["Comfortable drop length", "Warm translucent color", "Secure hook closure"],
      specifications: { availability: "Low stock", material: "Gold tone and amber glass", size: "1.5-inch drop" },
      price: 54,
      category: "earrings",
      featured: false,
      imageCount: 5,
      tags: ["amber", "gold", "drop", "warm"],
      accentColor: "#9b713e",
    }),
    createProduct({
      id: "product-003",
      name: "Midnight Onyx Pendant",
      description: "A smooth dark stone in a simple setting that brings quiet contrast to any outfit.",
      features: ["Clean oval silhouette", "Adjustable chain", "Day-to-evening style"],
      specifications: { availability: "In stock", material: "Sterling silver and onyx", size: "18 to 20-inch chain" },
      price: 72,
      category: "necklaces",
      featured: false,
      imageCount: 5,
      tags: ["onyx", "silver", "black", "pendant"],
      accentColor: "#4f5356",
    }),
    createProduct({
      id: "product-004",
      name: "Meadow Charm Bracelet",
      description: "A delicate bracelet with nature-inspired details and a relaxed, familiar feel.",
      features: ["Adjustable fit", "Small botanical charms", "Comfortable everyday weight"],
      specifications: { availability: "In stock", material: "Antique gold tone", size: "7 to 8 inches" },
      price: 58,
      category: "bracelets",
      featured: false,
      imageCount: 4,
      tags: ["charm", "botanical", "gold", "nature"],
      accentColor: "#78825c",
    }),
    createProduct({
      id: "product-005",
      name: "Heirloom Heart Locket",
      description: "A petite locket made for a small photograph, note, or meaningful keepsake.",
      features: ["Opens for a personal keepsake", "Traditional polished finish", "Thoughtful gift choice"],
      specifications: { availability: "In stock", material: "Warm gold tone", size: "20-inch chain" },
      price: 64,
      category: "necklaces",
      featured: false,
      imageCount: 4,
      tags: ["locket", "heart", "keepsake", "gift"],
      accentColor: "#9a724b",
    }),
    createProduct({
      id: "product-006",
      name: "Ruby Drop Earrings",
      description: "Rich red drops add a confident touch of color without feeling overly formal.",
      features: ["Faceted ruby-colored glass", "Light-catching movement", "Simple lever-back closure"],
      specifications: { availability: "Limited availability", material: "Gold tone and ruby glass", size: "1.25-inch drop" },
      price: 62,
      category: "earrings",
      featured: false,
      imageCount: 4,
      tags: ["ruby", "red", "drop", "gold"],
      accentColor: "#8e3d45",
    }),
    createProduct({
      id: "product-007",
      name: "Classic Pearl Trio",
      description: "Three coordinated pearl-inspired pieces make a polished and wonderfully useful gift.",
      features: ["Coordinated three-piece set", "Soft ivory luster", "Gift-ready presentation"],
      specifications: { availability: "In stock", material: "Pearl glass and gold tone", size: "Coordinated set" },
      price: 98,
      category: "gift-sets",
      featured: false,
      imageCount: 5,
      tags: ["pearl", "set", "classic", "gift"],
      accentColor: "#a58e69",
    }),
    createProduct({
      id: "product-008",
      name: "Golden Link Bracelet",
      description: "Rounded links and a softly polished finish make this bracelet easy to dress up or down.",
      features: ["Smooth rounded links", "Secure clasp", "Comfortable statement weight"],
      specifications: { availability: "Low stock", material: "Polished gold tone", size: "7.5 inches" },
      price: 76,
      category: "bracelets",
      featured: false,
      imageCount: 4,
      tags: ["gold", "link", "bracelet", "classic"],
      accentColor: "#a47d3f",
    }),
    createProduct({
      id: "product-009",
      name: "Silver Leaf Brooch",
      description: "A graceful leaf design that adds a quiet point of interest to a jacket, scarf, or bag.",
      features: ["Textured leaf detail", "Secure pin back", "Elegant nature-inspired shape"],
      specifications: { availability: "In stock", material: "Brushed silver tone", size: "2.25 inches" },
      price: 46,
      category: "brooches",
      featured: true,
      imageCount: 4,
      tags: ["silver", "leaf", "brooch", "nature"],
      accentColor: "#68767a",
    }),
    createProduct({
      id: "product-010",
      name: "Two-Tone Circle Pendant",
      description: "Interlocking silver and gold circles create a versatile, balanced everyday necklace.",
      features: ["Easy two-tone styling", "Lightweight pendant", "Adjustable chain"],
      specifications: { availability: "In stock", material: "Silver and gold tone", size: "18 to 20-inch chain" },
      price: 66,
      category: "necklaces",
      featured: false,
      imageCount: 4,
      tags: ["two-tone", "circle", "silver", "gold"],
      accentColor: "#7c756a",
    }),
    createProduct({
      id: "product-011",
      name: "Rose Quartz Studs",
      description: "Soft blush stones bring a flattering hint of color to a simple, comfortable stud.",
      features: ["Low-profile setting", "Gentle blush color", "Comfortable for daily wear"],
      specifications: { availability: "In stock", material: "Rose quartz glass and gold tone", size: "8 mm" },
      price: 38,
      category: "earrings",
      featured: false,
      imageCount: 4,
      tags: ["rose quartz", "pink", "studs", "gift"],
      accentColor: "#b4827c",
    }),
    createProduct({
      id: "product-012",
      name: "Moonlight Square Pendant",
      description: "A softly geometric pendant with a pearly finish and a clean, modern outline.",
      features: ["Simple square silhouette", "Subtle light-catching surface", "Adjustable fine chain"],
      specifications: { availability: "In stock", material: "Silver tone and pearl glass", size: "18-inch chain" },
      price: 59,
      category: "necklaces",
      featured: false,
      imageCount: 4,
      tags: ["silver", "square", "pearl", "modern"],
      accentColor: "#7a8588",
    }),
    createProduct({
      id: "product-013",
      name: "Garnet Velvet Necklace",
      description: "Deep garnet color gives this refined necklace a rich look that remains easy to wear.",
      features: ["Deep wine-colored stones", "Gentle graduated design", "Secure lobster clasp"],
      specifications: { availability: "Limited availability", material: "Garnet glass and gold tone", size: "18 inches" },
      price: 84,
      category: "necklaces",
      featured: false,
      imageCount: 4,
      tags: ["garnet", "red", "necklace", "evening"],
      accentColor: "#6f3f46",
    }),
    createProduct({
      id: "product-014",
      name: "High Street Gold Hoops",
      description: "A polished medium hoop with a softly rounded profile and dependable everyday style.",
      features: ["Comfortable medium size", "Rounded polished shape", "Hinged closure"],
      specifications: { availability: "In stock", material: "Polished gold tone", size: "1-inch hoop" },
      price: 48,
      category: "earrings",
      featured: false,
      imageCount: 4,
      tags: ["gold", "hoops", "classic", "everyday"],
      accentColor: "#a3793f",
    }),
    createProduct({
      id: "product-015",
      name: "Holiday Star Pin",
      description: "A small starburst pin with just enough sparkle for celebrations and winter gatherings.",
      features: ["Light-catching crystal detail", "Secure pin closure", "Lovely on lapels and scarves"],
      specifications: { availability: "Seasonal", material: "Gold tone and crystal glass", size: "1.75 inches" },
      price: 44,
      category: "brooches",
      featured: false,
      imageCount: 4,
      tags: ["star", "pin", "crystal", "holiday"],
      accentColor: "#9f7650",
    }),
    createProduct({
      id: "product-016",
      name: "Caramel Agate Pendant",
      description: "A warm, earthy stone pendant with natural-looking variation and a smooth finish.",
      features: ["One-of-a-kind color variation", "Smooth oval shape", "Longer adjustable chain"],
      specifications: { availability: "Made in small batches", material: "Agate-style stone and gold tone", size: "24-inch chain" },
      price: 78,
      category: "necklaces",
      featured: false,
      imageCount: 4,
      tags: ["agate", "brown", "earthy", "pendant"],
      accentColor: "#836750",
    }),
    createProduct({
      id: "product-017",
      name: "Signature Silver Cuff",
      description: "A clean, softly curved cuff that slips on easily and complements nearly everything.",
      features: ["Open adjustable shape", "Smooth polished finish", "Comfortable rounded edges"],
      specifications: { availability: "In stock", material: "Polished silver tone", size: "Adjustable" },
      price: 70,
      category: "bracelets",
      featured: false,
      imageCount: 4,
      tags: ["silver", "cuff", "minimal", "everyday"],
      accentColor: "#6f7c80",
    }),
    createProduct({
      id: "product-018",
      name: "Soft Gold Hoops",
      description: "Slim, lightweight hoops with a warm satin finish and an unfussy everyday scale.",
      features: ["Lightweight construction", "Soft satin finish", "Simple click closure"],
      specifications: { availability: "In stock", material: "Satin gold tone", size: "0.75-inch hoop" },
      price: 42,
      category: "earrings",
      featured: true,
      imageCount: 4,
      tags: ["gold", "hoops", "lightweight", "minimal"],
      accentColor: "#aa8749",
    }),
    createProduct({
      id: "product-019",
      name: "Harvest Stone Bracelet",
      description: "A comfortable strand of warm, earthy colors inspired by autumn leaves and sunlit wood.",
      features: ["Flexible stretch fit", "Warm mixed stone colors", "Easy pull-on style"],
      specifications: { availability: "Seasonal", material: "Mixed stone-style beads", size: "Fits 6.5 to 7.5 inches" },
      price: 52,
      category: "bracelets",
      featured: false,
      imageCount: 4,
      tags: ["stone", "autumn", "warm", "bracelet"],
      accentColor: "#8a6545",
    }),
    createProduct({
      id: "product-020",
      name: "Golden Dew Pendant",
      description: "A petite teardrop pendant with a polished finish that catches the light beautifully.",
      features: ["Delicate teardrop shape", "Easy everyday scale", "Adjustable chain"],
      specifications: { availability: "In stock", material: "Polished gold tone", size: "16 to 18-inch chain" },
      price: 56,
      category: "necklaces",
      featured: false,
      imageCount: 4,
      tags: ["gold", "teardrop", "delicate", "pendant"],
      accentColor: "#a67d3d",
    }),
    createProduct({
      id: "product-021",
      name: "October Opal Brooch",
      description: "Soft shifting color gives this rounded brooch an elegant, light-filled presence.",
      features: ["Opal-inspired center", "Subtle iridescent color", "Secure locking pin"],
      specifications: { availability: "Limited availability", material: "Opal glass and gold tone", size: "2 inches" },
      price: 74,
      category: "brooches",
      featured: false,
      imageCount: 4,
      tags: ["opal", "brooch", "iridescent", "gift"],
      accentColor: "#8d725f",
    }),
    createProduct({
      id: "product-022",
      name: "Twisted Silver Ring",
      description: "Two slender silver bands meet in a gentle twist for a comfortable, understated look.",
      features: ["Smooth crossover shape", "Low everyday profile", "Easy to pair with other rings"],
      specifications: { availability: "Sizes 6 to 9", material: "Polished silver tone", size: "Choose your size" },
      price: 45,
      category: "rings",
      featured: false,
      imageCount: 4,
      tags: ["silver", "ring", "twist", "minimal"],
      accentColor: "#717d80",
    }),
    createProduct({
      id: "product-023",
      name: "Mountain Stone Gift Set",
      description: "A coordinated necklace and earring set in calm stone colors inspired by open landscapes.",
      features: ["Coordinated two-piece set", "Soft natural color palette", "Ready for thoughtful gifting"],
      specifications: { availability: "Low stock", material: "Mixed stone-style glass and silver tone", size: "18-inch necklace" },
      price: 112,
      category: "gift-sets",
      featured: false,
      imageCount: 5,
      tags: ["stone", "set", "silver", "gift"],
      accentColor: "#626c69",
    }),
    createProduct({
      id: "product-024",
      name: "Green Glass Drop Earrings",
      description: "Clear green drops bring fresh color and a graceful sense of movement.",
      features: ["Lightweight faceted drops", "Fresh botanical color", "Secure lever-back closure"],
      specifications: { availability: "In stock", material: "Green glass and gold tone", size: "1.25-inch drop" },
      price: 58,
      category: "earrings",
      featured: false,
      imageCount: 3,
      tags: ["green", "glass", "drop", "botanical"],
      accentColor: "#5f8065",
    }),
    createProduct({
      id: "product-025",
      name: "Emerald Market Ring",
      description: "A rich green centerpiece in a clean setting that lets the color speak for itself.",
      features: ["Deep emerald-colored stone", "Low comfortable setting", "Simple polished band"],
      specifications: { availability: "Sizes 6 to 9", material: "Emerald glass and gold tone", size: "Choose your size" },
      price: 82,
      category: "rings",
      featured: false,
      imageCount: 4,
      tags: ["emerald", "green", "ring", "gold"],
      accentColor: "#3f6d50",
    }),
    createProduct({
      id: "product-026",
      name: "Orchard Charm Bracelet",
      description: "Tiny leaf and fruit-inspired charms create a warm, cheerful bracelet with vintage appeal.",
      features: ["Small detailed charms", "Adjustable extension chain", "Warm antique finish"],
      specifications: { availability: "Seasonal", material: "Antique gold tone and glass", size: "7 to 8 inches" },
      price: 64,
      category: "bracelets",
      featured: false,
      imageCount: 4,
      tags: ["orchard", "charm", "bracelet", "vintage"],
      accentColor: "#8f604b",
    }),
    createProduct({
      id: "product-027",
      name: "Peach Moonstone Pendant",
      description: "A soft peach-toned stone gives this delicate pendant a warm and flattering glow.",
      features: ["Soft luminous color", "Simple oval setting", "Fine adjustable chain"],
      specifications: { availability: "In stock", material: "Moonstone-style glass and gold tone", size: "18 to 20-inch chain" },
      price: 69,
      category: "necklaces",
      featured: false,
      imageCount: 4,
      tags: ["peach", "moonstone", "pendant", "soft"],
      accentColor: "#b67f68",
    }),
    createProduct({
      id: "product-028",
      name: "Petite Pearl Studs",
      description: "Small pearl-inspired studs with a neat profile and a timeless, polished finish.",
      features: ["Petite everyday size", "Soft ivory luster", "Comfortable post back"],
      specifications: { availability: "In stock", material: "Pearl glass and gold tone", size: "6 mm" },
      price: 34,
      category: "earrings",
      featured: false,
      imageCount: 4,
      tags: ["pearl", "studs", "petite", "classic"],
      accentColor: "#a39475",
    }),
    createProduct({
      id: "product-029",
      name: "Archive Collection",
      description: "A look through earlier pieces, retired designs, and past limited selections.",
      features: ["Past collection reference", "Useful for custom inquiries", "Additional views included"],
      specifications: { availability: "Archive only", material: "Varied materials", size: "Contact for details" },
      price: null,
      category: "gift-sets",
      featured: false,
      imageCount: 8,
      tags: ["archive", "past collection", "reference"],
      accentColor: "#6c7473",
    }),
  ];

  const productData = Object.fromEntries(productList.map((product) => [product.id, product]));

  window.StorefrontProducts = productData;
})(window);
