// Catalog data only. Site-level settings live in site-config.js.

const treatData = {
  "bday-cake": {
    name: "Birthday Cake Cookie",
    vibe: "#e023c7",
    ingredients: "birthday cake oreo, rainbow sprinkles, butter, {brown & granulated} sugar, eggs, white chocolate, (ap) flour, birthday cake batter extract, baking soda, baking powder, cornstarch, salt,",
    allergens: "Dairy, Flour (gluten)",
    images: [
      "images/bday-cake-main.webp",
      "images/bday-cake-1.webp",
      "images/bday-cake-2.webp",
      "images/bday-cake-3.webp",
      "images/bday-cake-4.webp",
    ],
  },
  "dulce-bisicoff": {
    name: "Dulce de Leche Biscoff Cookie",
    vibe: "#99671c",
    ingredients: "sweetened condensed milk, biscoff, butter, {brown & granulated} sugar, eggs, white chocolate, (ap) flour, baking soda, baking powder, salt, cinnamon",
    allergens: "Dairy, Flour (gluten)",
    images: [
      "images/dulce-bisicoff-main.webp",
      "images/dulce-bisicoff-1.webp",
      "images/dulce-bisicoff-2.webp",
      "images/dulce-bisicoff-3.webp",
      "images/dulce-bisicoff-4.webp",
    ],
  },
  "smoreo": {
    name: "S'moreo Cookie",
    vibe: "#000000",
    ingredients: "marshmallow, oreo cookies, butter, sugar, molassas, eggs, semi-sweet chocolate, white chocolate, (ap) flour, cornstarch, baking soda, baking powder, salt, cocoa power",
    allergens: "Dairy",
    images: [
      "images/smoreo-main.webp",
      "images/smoreo-1.webp",
      "images/smoreo-2.webp",
      "images/smoreo-3.webp",
      "images/smoreo-4.webp",
    ],
  },
  "kitchen-sink": {
    name: "Kitchen Sink Cookie",
    vibe: "#f5ca3c",
    ingredients: "butter, sugar, molassas, eggs, semi-sweet chocolate, gluten Free (gf) flour, (gf) pretzel, (gf) potato chips, caramel bits, cinnamon, baking Soda, salt",
    allergens: "Dairy",
    images: [
      "images/kitchen-sink-main.webp",
      "images/kitchen-sink-1.webp",
      "images/kitchen-sink-2.webp",
      "images/kitchen-sink-3.webp",
    ],
  },
  "biscoff-billionaire": {
    name: "Biscoff Billionaire",
    vibe: "#975b22",
    ingredients: "biscoff cookie, butter, biscoff cookie butter, sweetned condensed milk, sugar, sugar syrup, white & semi-Sweet chocolate chips",
    allergens: "Flour (gluetn), Dairy",
    images: [
      "images/biscoff-b-main.webp",
      "images/biscoff-b-1.webp",
      "images/biscoff-b-2.webp",
      "images/biscoff-b-3.webp",
    ],
  },
  "chocoberry": {
    name: "Strawberry Covered Chocolate Cookie",
    vibe: "#9d0000",
    ingredients: "freeze dried strawberry, semi-Sweet chocolate, butter, sugar, egg, molasses, salt, baking soda",
    allergens: "Flour (gluetn), Dairy",
    images: [
      "images/chocoberry-main.webp",
      "images/chocoberry-1.webp",
      "images/chocoberry-2.webp",
      "images/chocoberry-3.webp",
    ],
  },
  "choclate-smores'2": {
    name: "Chocolate Chips Smores Cookie",
    vibe: "#9e4700",
    ingredients: "classic, jaytreat cookie base, cinnamon, {milk,white, dark} choclate chips &, toasted marshmallow, graham cracker,",
    allergens: "Flour (gluetn), Dairy, Gelatin",
    images: [
      "images/smores-chip'2-main.webp",
      "images/smores-chip'2-1.webp",
      "images/smores-chip'2-2.webp",
      "images/smores-chip'2-3.webp",
      "images/smores-chip'2-4.webp",
    ],
  },
  "caramel-snickerdoodle": {
    name: "Carmel Snickerdoodle Cookie Sandwich",
    vibe: "#ffbb5cc9",
    ingredients: "butter, sugar, brown Sugar, eggs, flour, baking Powder, salt, cornstarch, cinnamon, cream of tartar",
    allergens: "Flour (Gluetn), Cinnamon",
    images: [
      "images/caramel-snickerdoodle-main.webp",
      "images/caramel-snickerdoodle-1.webp",
      "images/caramel-snickerdoodle-2.webp",
      "images/caramel-snickerdoodle-3.webp",
    ],
  },
  "biscoff-brownie": {
    name: "British Smores Brownie",
    vibe: "#381300b5",
    ingredients: "marshmallows, semi sweet & dark chocolate chips, butter, sugar, brown Sugar, eggs, flour, baking powder, salt, cornstarch, cocoa powder, biscoff Spread, biscoff Cookie",
    allergens: "Flour (Gluetn), Gelatin",
    images: [
      "images/biscoff-brownie-main.webp",
      "images/biscoff-brownie-1.webp",
      "images/biscoff-brownie-2.webp",
      "images/biscoff-brownie-poster.webp",
    ],
  },
  "cookies-cream": {
    name: "Cookies & Cream",
    vibe: "#000000b5",
    ingredients: "oreos (golden & original), semi sweet & white chocolate chips Butter, sugar, brown Sugar, eggs, flour, baking soda, salt, cornstarch,",
    allergens: "Flour (Gluetn)",
    images: [
      "images/cookies-cream-main.webp",
      "images/cookies-cream-1.webp",
      "images/cookies-cream-2.webp",
      "images/cookies-cream-3.webp",
    ],
  },
  "fudge-brookie": {
    name: "Heath Oreo Brookie Fudge Bomb",
    vibe: "#822300b5",
    ingredients: "heath, cookie dough oreo, semisweet chocolate chips, butter, sugar, salt, cocoa powder",
    allergens: "Flour (Gluetn)",
    images: [
      "images/fudge-brookie-main.webp",
      "images/fudge-brookie-1.webp",
      "images/fudge-brookie-2.webp",
      "images/fudge-brookie-poster.webp",
    ],
  },
  "biscoff-crispy": {
    name: "Biscoff Rice Crisp treat",
    vibe: "#0095f2",
    ingredients: "chewy rice crispy infused with biscoff butter, finished with a biscoff white choclate and encrusted with more biscoff powder",
    allergens: "Cinnamon, Gelatin",
    images: [
      "images/biscoff-crispy-main.webp",
      "images/biscoff-crispy-1.webp",
      "images/biscoff-crispy-2.webp",
      "images/biscoff-crispy-poster.webp",
    ],
  },
  "velvet-cheesecake": {
    name: "Dark Velvet Cheesecake Cookie",
    vibe: "#3e0f04",
    ingredients: "chocolate cookie base, unprocessed cocoa powder, white chocolate chips, cream cheese filling",
    allergens: "Flour (gluetn), Dairy, Cocoa",
    youtubeID: "https://www.youtube.com/shorts/h2pDgsDiEv8",
    images: [
      "images/velvet-cheesecake-main.webp",
      "images/velvet-cheesecake-1.webp",
      "images/velvet-cheesecake-2.webp",
      "images/velvet-cheesecake-poster.webp",
    ],
  },
  "british-smores": {
    name: "British Smores Cookie",
    vibe: "#8e3d00",
    ingredients: "classic, jaytreat cookie base, cinnamon, white choclate chips, biscoff, biscoff cookie butter, toasted marshmallow",
    allergens: "Flour (gluetn), Dairy",
    youtubeID: "https://www.youtube.com/shorts/wIAtMzUSFHI",
    images: [
      "images/british-main.webp",
      "images/british-1.webp",
      "images/british-2.webp",
      "images/british-poster.webp",
    ],
  },
  "santas-cookies": {
    name: "Santas Cookies",
    vibe: "#ff2710",
    ingredients: "classic jaytreat cookie base, chocolate & white peppermint chocolate covered pretzels, chocolate covered caramels & almonds",
    allergens: "Flour (gluetn), Almonds",
    youtubeID: "https://www.youtube.com/shorts/V8w1FR6SCSM",
    images: [
      "images/santa-main.webp",
      "images/santa-1.webp",
      "images/santa-2.webp",
      "images/santa-poster.webp",
    ],
  },
  "basque-cheesecake": {
    name: "Caramel Biscoff Basque Cheesecake",
    vibe: "#6f5948",
    ingredients: "biscoff cookie base, salted caramel, cream cheese.",
    allergens: "Nutmeg",
    youtubeID: "https://www.youtube.com/shorts/g6cSvJr3fzw",
    images: [
      "images/basquecake-main.webp",
      "images/basquecake-1.webp",
      "images/basquecake-2.webp",
      "images/basquecake-poster.webp",
    ],
  },
  "choclate-smores": {
    name: "Chocolate Chips Smores Cookie",
    vibe: "#ffe6d2",
    ingredients: "classic, jaytreat cookie base, cinnamon, semi-sweet choclate chips, toasted marshmallow",
    allergens: "Flour (gluetn), Dairy, Gelatin",
    youtubeID: "https://www.youtube.com/shorts/SEFPr8NGXiY",
    images: [
      "images/smores-chip-main.webp",
      "images/smores-chip-1.webp",
      "images/smores-chip-2.webp",
      "images/smores-chip-poster.webp",
    ],
  },
  "bannana-bread": {
    name: "Bannana Bread Cookies",
    vibe: "#ffea00",
    ingredients: "bannana bread-cookie hybrid that is soft and chewy but not too sweet.",
    allergens: "Flour (gluetn), Dairy, Bannana",
    youtubeID: "https://www.youtube.com/shorts/Q-Cp2_iJrfc",
    images: [
      "images/bannana-cookie-main.webp",
      "images/bannana-cookie-1.webp",
      "images/bannana-cookie-2.webp",
      "images/bannana-cookie-poster.webp",
    ],
  },
  "pumpkin-kup": {
    name: "Iced Spiced Pumpkin Kupz",
    vibe: "#a44f00",
    ingredients: "fluffy yellow cake with cinnamon sugar topping, and finished with maple spiced icing",
    allergens: "Flour (gluetn), Dairy, Cinnamon, Nutmeg",
    images: [
      "images/pump-kup-main.webp",
      "images/pump-kup-1.webp",
      "images/pump-kup-2.webp",
      "images/pump-kup-poster.webp",
    ],
  },
  "golden-smore": {
    name: "Golden Smoreo Cookie",
    vibe: "#a44f00",
    ingredients: "classic jaytreat cookie base with a golden oreo surprise on the bottom, and a marshmallow one on top.",
    allergens: "Flour (gluetn), Dairy, Cinnamon",
    images: [
      "images/golden-smoreo-main.webp",
      "images/golden-smoreo-1.webp",
      "images/golden-smoreo-2.webp",
      "images/golden-smoreo-poster.webp",
    ],
  },
  "cookies-scream": {
    name: "Cookies & Scream Brownie",
    vibe: "#ff5100b5",
    ingredients: "halloween Oreos, chocolate goodness.",
    allergens: "Flour (Gluetn)",
    images: [
      "images/cookies-scream-main.webp",
      "images/cookies-scream-1.webp",
      "images/cookies-scream-2.webp",
      "images/cookies-scream-poster.webp",
    ],
  },
  "smores-pc": {
    name: "Pretzel Caramel Smores Cookie",
    vibe: "#5b3614",
    ingredients: "classic jaytreat cookie stuffed with pretzels, caramel, chocolate chips, and topped with a toasted marsh",
    allergens: "Flour (gluetn), Dairy, Cinnamon",
    images: [
      "images/smores-pc-main.webp",
      "images/smores-pc-1.webp",
      "images/smores-pc-2.webp",
      "images/smores-pc-poster.webp",
    ],
  },
  "mountain-cookie": { 
    name: "Mountain Cookie",
    vibe: "#000000",
    ingredients: "heath, biscoff, oreo, cookie!",
    allergens: "Flour (gluetn)",
    images: [
      "images/mountain-cookie-main.webp",
      "images/mountain-cookie-1.webp",
      "images/mountain-cookie-2.webp",
      "images/mountain-cookie-3.webp",
      "images/mountain-cookie-poster.webp",
    ],
  },
  "matcha-cookie": { 
    name: "Matcha Cookie",
    vibe: "#44ff00",
    ingredients: "matcha, cream cheese, honey caramel, oatmeal",
    allergens: "Flour (gluetn), Cream Cheese, Performative nature",
    images: [
      "images/matcha-cookie-main.webp",
      "images/matcha-cookie-1.webp",
      "images/matcha-cookie-poster.webp",
    ],  
  },
  "dubai-cookie": { 
    name: "Dubai Cookie",
    vibe: "#114a00",
    ingredients: "classic Jaytreat, with dubai pistachio filling and chocolate topping.",
    allergens: "Flour (gluetn) gelatin, peach",
    images: [
      "images/dubai-cookie-main.webp",
      "images/dubai-cookie-1.webp",
      "images/dubai-cookie-2.webp",
      "images/dubai-cookie-poster.webp",
    ],
  },
  "apple-studel": { 
    name: "Apple Strudel Kup",
    vibe: "#ff3006",
    ingredients: "delicious cookie cup with apple filling topped with crunchy cinnamon sugar strudel",
    allergens: "Flour (gluetn) gelatin Apple" ,
    images: [
      "images/apple-strudel-main.webp",
      "images/apple-strudel-1.webp",
      "images/apple-strudel-2.webp",
      "images/apple-strudel-poster.webp",
    ],
  },
  "peach-cream": { 
    name: "Peaches & Cream Cookie",
    vibe: "#ffaa64",
    ingredients: "classic jaytreat cookie base mixed with peach puree and white choclate chips",
    allergens: "Flour (gluetn) Gelatin, Peach",
    images: [
      "images/peach-cream-main.webp",
      "images/peach-cream-1.webp",
      "images/peach-cream-2.webp",
      "images/peach-cream-poster.webp",
    ],
  },
  "kid-kup": { 
    name: "Kid Kups",
    vibe: "#ffd900",
    ingredients: "everything you love in a cup (marshmallow, cookie, chocolate, pretzel, m&m)",
    allergens: "Flour (gluetn) Gelatin",
    images: [
      "images/kid-kup-main.webp",
      "images/kid-kup-1.webp",
      "images/kid-kup-2.webp",
      "images/kid-kup-poster.webp",
    ],
  },
  "throwbacks": {
    name: "Throwbacks",
    vibe: "#ffffff",
    ingredients: "idk, a bunch of em, these are oldies",
    allergens: "I think one had peanuts",
    images: [
      "images/other-main.webp",
      "images/other-1.webp",
      "images/other-2.webp",
      "images/other-3.webp",
      "images/other-4.webp",
      "images/other-5.webp",
      "images/other-6.webp",
      "images/other-7.webp",
    ],
  },
};

window.JayTreatsData = treatData;
window.treatData = treatData;
